import { GymManagerRootRoute } from "./GymManagerRootRoute";
import {
  accessRoute,
  analyticsRoute,
  announcementsRoute,
  attendanceRoute,
  coachingRoute,
  competitionsRoute,
  createMemberRoute,
  homeRoute,
  inventoryRoute,
  marketingRoute,
  membersRoute,
  notificationsRoute,
  pricingRoute,
  settingsRoute,
  staffRoute,
  storeRoute,
  subscriptionsRoute,
} from "./GymManagerRoutes";

export const GymManagerRootTree = GymManagerRootRoute.addChildren([
  homeRoute,
  subscriptionsRoute,
  membersRoute,
  createMemberRoute,
  notificationsRoute,
  analyticsRoute,
  settingsRoute,
  accessRoute,
  attendanceRoute,
  pricingRoute,
  staffRoute,
  coachingRoute,
  announcementsRoute,
  inventoryRoute,
  storeRoute,
  competitionsRoute,
  marketingRoute,
]);
