export enum AuthErrorCode {
  // Authentication errors
  INVALID_CREDENTIALS = 'AUTH_001',
  ACCOUNT_DEACTIVATED = 'AUTH_002',
  EMAIL_NOT_VERIFIED = 'AUTH_003',
  INVALID_REFRESH_TOKEN = 'AUTH_004',
  NO_TOKEN_PROVIDED = 'AUTH_005',
  INVALID_TOKEN = 'AUTH_006',

  // Registration errors
  USER_ALREADY_EXISTS = 'AUTH_007',
  EMAIL_ALREADY_VERIFIED = 'AUTH_008',
  USER_NOT_FOUND = 'AUTH_009',

  // Verification errors
  INVALID_VERIFICATION_TOKEN = 'AUTH_010',
  EXPIRED_VERIFICATION_TOKEN = 'AUTH_011',

  // Password reset errors
  INVALID_RESET_TOKEN = 'AUTH_012',
  EXPIRED_RESET_TOKEN = 'AUTH_013',

  // OAuth errors
  GOOGLE_AUTH_FAILED = 'AUTH_014',
  GOOGLE_USER_INFO_FAILED = 'AUTH_015',
}

export enum UserErrorCode {
  // User not found
  USER_NOT_FOUND = 'USER_001',

  // User update errors
  EMAIL_ALREADY_IN_USE = 'USER_002',
  USERNAME_ALREADY_IN_USE = 'USER_003',
  INVALID_USER_DATA = 'USER_004',
  CANNOT_UPDATE_EMAIL = 'USER_005',

  // User role errors
  INVALID_ROLE = 'USER_006',
  CANNOT_CHANGE_OWN_ROLE = 'USER_007',
  INSUFFICIENT_PERMISSIONS = 'USER_008',

  // User status errors
  USER_ALREADY_ACTIVE = 'USER_009',
  USER_ALREADY_DEACTIVATED = 'USER_010',
  CANNOT_DEACTIVATE_SELF = 'USER_011',

  // Profile errors
  INVALID_PROFILE_DATA = 'USER_012',
  PROFILE_UPDATE_FAILED = 'USER_013',
}

