import { SupportedCurrency } from "./common";

export type AppLanguage = "en" | "fr" | "ar";

export const LANGUAGES = {
  en: {
    label: "English",
    locale: "en-US",
    flag: "🇺🇸",
    icon: "us",
    dir: "ltr",
  },
  fr: {
    label: "Français",
    locale: "fr-FR",
    flag: "🇫🇷",
    icon: "fr",
    dir: "ltr",
  },
  ar: {
    label: "العربية",
    locale: "ar-DZ",
    flag: "🇩🇿",
    icon: "dz",
    dir: "rtl",
  },
} satisfies Record<
  AppLanguage,
  {
    label: string;
    locale: string;
    flag: string;
    icon: string;
    dir: "ltr" | "rtl";
  }
>;

// Derived constants
export const DEFAULT_LANGUAGE: AppLanguage = "en";
export const SUPPORTED_LANGUAGES = Object.keys(LANGUAGES) as AppLanguage[];
export const RTL_LANGUAGES = SUPPORTED_LANGUAGES.filter(
  (lng) => LANGUAGES[lng].dir === "rtl"
);

export const DEFAULT_CURRENCY: SupportedCurrency = "USD";

export const SUPPORTED_TIMEZONES = [
  "UTC",
  "America/New_York",
  "Europe/London",
  "Europe/Paris",
  "Asia/Dubai",
  "Asia/Riyadh",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Algiers",
  "Africa/Tunis",
  "Africa/Tripoli",
  "Africa/Khartoum",
  "Africa/Nairobi",
  "Africa/Johannesburg",
  "Africa/Lagos",
  "Africa/Accra",
  "Africa/Abidjan",
  "Africa/Addis_Ababa",
  "Africa/Luanda",
];

export const SUPPORTED_REGIONS = {
  // Africa
  DZ: { name: "Algeria", currency: "DZD" },
  AO: { name: "Angola", currency: "AOA" },
  BJ: { name: "Benin", currency: "XOF" },
  BW: { name: "Botswana", currency: "BWP" },
  BF: { name: "Burkina Faso", currency: "XOF" },
  BI: { name: "Burundi", currency: "BIF" },
  CM: { name: "Cameroon", currency: "XAF" },
  CV: { name: "Cape Verde", currency: "CVE" },
  CF: { name: "Central African Republic", currency: "XAF" },
  TD: { name: "Chad", currency: "XAF" },
  KM: { name: "Comoros", currency: "KMF" },
  CG: { name: "Congo", currency: "XAF" },
  CD: { name: "Congo (DRC)", currency: "CDF" },
  CI: { name: "Côte d'Ivoire", currency: "XOF" },
  DJ: { name: "Djibouti", currency: "DJF" },
  EG: { name: "Egypt", currency: "EGP" },
  GQ: { name: "Equatorial Guinea", currency: "XAF" },
  ER: { name: "Eritrea", currency: "ERN" },
  ET: { name: "Ethiopia", currency: "ETB" },
  GA: { name: "Gabon", currency: "XAF" },
  GM: { name: "Gambia", currency: "GMD" },
  GH: { name: "Ghana", currency: "GHS" },
  GN: { name: "Guinea", currency: "GNF" },
  GW: { name: "Guinea-Bissau", currency: "XOF" },
  KE: { name: "Kenya", currency: "KES" },
  LS: { name: "Lesotho", currency: "LSL" },
  LR: { name: "Liberia", currency: "LRD" },
  LY: { name: "Libya", currency: "LYD" },
  MG: { name: "Madagascar", currency: "MGA" },
  MW: { name: "Malawi", currency: "MWK" },
  ML: { name: "Mali", currency: "XOF" },
  MR: { name: "Mauritania", currency: "MRU" },
  MU: { name: "Mauritius", currency: "MUR" },
  YT: { name: "Mayotte", currency: "EUR" },
  MA: { name: "Morocco", currency: "MAD" },
  MZ: { name: "Mozambique", currency: "MZN" },
  NA: { name: "Namibia", currency: "NAD" },
  NE: { name: "Niger", currency: "XOF" },
  NG: { name: "Nigeria", currency: "NGN" },
  RE: { name: "Réunion", currency: "EUR" },
  RW: { name: "Rwanda", currency: "RWF" },
  ST: { name: "São Tomé and Príncipe", currency: "STN" },
  SN: { name: "Senegal", currency: "XOF" },
  SC: { name: "Seychelles", currency: "SCR" },
  SL: { name: "Sierra Leone", currency: "SLL" },
  SO: { name: "Somalia", currency: "SOS" },
  ZA: { name: "South Africa", currency: "ZAR" },
  SS: { name: "South Sudan", currency: "SSP" },
  SD: { name: "Sudan", currency: "SDG" },
  SZ: { name: "Eswatini", currency: "SZL" },
  TZ: { name: "Tanzania", currency: "TZS" },
  TG: { name: "Togo", currency: "XOF" },
  TN: { name: "Tunisia", currency: "TND" },
  UG: { name: "Uganda", currency: "UGX" },
  ZM: { name: "Zambia", currency: "ZMW" },
  ZW: { name: "Zimbabwe", currency: "ZWL" },

  // Asia
  AF: { name: "Afghanistan", currency: "AFN" },
  AM: { name: "Armenia", currency: "AMD" },
  AZ: { name: "Azerbaijan", currency: "AZN" },
  BH: { name: "Bahrain", currency: "BHD" },
  BD: { name: "Bangladesh", currency: "BDT" },
  BT: { name: "Bhutan", currency: "BTN" },
  BN: { name: "Brunei", currency: "BND" },
  KH: { name: "Cambodia", currency: "KHR" },
  CN: { name: "China", currency: "CNY" },
  GE: { name: "Georgia", currency: "GEL" },
  HK: { name: "Hong Kong", currency: "HKD" },
  IN: { name: "India", currency: "INR" },
  ID: { name: "Indonesia", currency: "IDR" },
  IR: { name: "Iran", currency: "IRR" },
  IQ: { name: "Iraq", currency: "IQD" },
  IL: { name: "Israel", currency: "ILS" },
  JP: { name: "Japan", currency: "JPY" },
  JO: { name: "Jordan", currency: "JOD" },
  KZ: { name: "Kazakhstan", currency: "KZT" },
  KW: { name: "Kuwait", currency: "KWD" },
  KG: { name: "Kyrgyzstan", currency: "KGS" },
  LA: { name: "Laos", currency: "LAK" },
  LB: { name: "Lebanon", currency: "LBP" },
  MO: { name: "Macau", currency: "MOP" },
  MY: { name: "Malaysia", currency: "MYR" },
  MV: { name: "Maldives", currency: "MVR" },
  MN: { name: "Mongolia", currency: "MNT" },
  MM: { name: "Myanmar", currency: "MMK" },
  NP: { name: "Nepal", currency: "NPR" },
  KP: { name: "North Korea", currency: "KPW" },
  OM: { name: "Oman", currency: "OMR" },
  PK: { name: "Pakistan", currency: "PKR" },
  PS: { name: "Palestine", currency: "ILS" },
  PH: { name: "Philippines", currency: "PHP" },
  QA: { name: "Qatar", currency: "QAR" },
  SA: { name: "Saudi Arabia", currency: "SAR" },
  SG: { name: "Singapore", currency: "SGD" },
  KR: { name: "South Korea", currency: "KRW" },
  LK: { name: "Sri Lanka", currency: "LKR" },
  SY: { name: "Syria", currency: "SYP" },
  TW: { name: "Taiwan", currency: "TWD" },
  TJ: { name: "Tajikistan", currency: "TJS" },
  TH: { name: "Thailand", currency: "THB" },
  TL: { name: "Timor-Leste", currency: "USD" },
  TR: { name: "Turkey", currency: "TRY" },
  TM: { name: "Turkmenistan", currency: "TMT" },
  AE: { name: "United Arab Emirates", currency: "AED" },
  UZ: { name: "Uzbekistan", currency: "UZS" },
  VN: { name: "Vietnam", currency: "VND" },
  YE: { name: "Yemen", currency: "YER" },

  // Europe
  AX: { name: "Åland Islands", currency: "EUR" },
  AL: { name: "Albania", currency: "ALL" },
  AD: { name: "Andorra", currency: "EUR" },
  AT: { name: "Austria", currency: "EUR" },
  BY: { name: "Belarus", currency: "BYN" },
  BE: { name: "Belgium", currency: "EUR" },
  BA: { name: "Bosnia and Herzegovina", currency: "BAM" },
  BG: { name: "Bulgaria", currency: "BGN" },
  HR: { name: "Croatia", currency: "EUR" },
  CY: { name: "Cyprus", currency: "EUR" },
  CZ: { name: "Czech Republic", currency: "CZK" },
  DK: { name: "Denmark", currency: "DKK" },
  EE: { name: "Estonia", currency: "EUR" },
  FO: { name: "Faroe Islands", currency: "DKK" },
  FI: { name: "Finland", currency: "EUR" },
  FR: { name: "France", currency: "EUR" },
  DE: { name: "Germany", currency: "EUR" },
  GI: { name: "Gibraltar", currency: "GIP" },
  GR: { name: "Greece", currency: "EUR" },
  GG: { name: "Guernsey", currency: "GBP" },
  HU: { name: "Hungary", currency: "HUF" },
  IS: { name: "Iceland", currency: "ISK" },
  IE: { name: "Ireland", currency: "EUR" },
  IM: { name: "Isle of Man", currency: "GBP" },
  IT: { name: "Italy", currency: "EUR" },
  JE: { name: "Jersey", currency: "GBP" },
  XK: { name: "Kosovo", currency: "EUR" },
  LV: { name: "Latvia", currency: "EUR" },
  LI: { name: "Liechtenstein", currency: "CHF" },
  LT: { name: "Lithuania", currency: "EUR" },
  LU: { name: "Luxembourg", currency: "EUR" },
  MT: { name: "Malta", currency: "EUR" },
  MD: { name: "Moldova", currency: "MDL" },
  MC: { name: "Monaco", currency: "EUR" },
  ME: { name: "Montenegro", currency: "EUR" },
  NL: { name: "Netherlands", currency: "EUR" },
  MK: { name: "North Macedonia", currency: "MKD" },
  NO: { name: "Norway", currency: "NOK" },
  PL: { name: "Poland", currency: "PLN" },
  PT: { name: "Portugal", currency: "EUR" },
  RO: { name: "Romania", currency: "RON" },
  RU: { name: "Russia", currency: "RUB" },
  SM: { name: "San Marino", currency: "EUR" },
  RS: { name: "Serbia", currency: "RSD" },
  SK: { name: "Slovakia", currency: "EUR" },
  SI: { name: "Slovenia", currency: "EUR" },
  ES: { name: "Spain", currency: "EUR" },
  SJ: { name: "Svalbard and Jan Mayen", currency: "NOK" },
  SE: { name: "Sweden", currency: "SEK" },
  CH: { name: "Switzerland", currency: "CHF" },
  UA: { name: "Ukraine", currency: "UAH" },
  GB: { name: "United Kingdom", currency: "GBP" },
  VA: { name: "Vatican City", currency: "EUR" },

  // North America
  AI: { name: "Anguilla", currency: "XCD" },
  AG: { name: "Antigua and Barbuda", currency: "XCD" },
  AW: { name: "Aruba", currency: "AWG" },
  BS: { name: "Bahamas", currency: "BSD" },
  BB: { name: "Barbados", currency: "BBD" },
  BZ: { name: "Belize", currency: "BZD" },
  BM: { name: "Bermuda", currency: "BMD" },
  BQ: { name: "Bonaire, Sint Eustatius and Saba", currency: "USD" },
  VG: { name: "British Virgin Islands", currency: "USD" },
  CA: { name: "Canada", currency: "CAD" },
  KY: { name: "Cayman Islands", currency: "KYD" },
  CR: { name: "Costa Rica", currency: "CRC" },
  CU: { name: "Cuba", currency: "CUP" },
  CW: { name: "Curaçao", currency: "ANG" },
  DM: { name: "Dominica", currency: "XCD" },
  DO: { name: "Dominican Republic", currency: "DOP" },
  SV: { name: "El Salvador", currency: "USD" },
  GL: { name: "Greenland", currency: "DKK" },
  GD: { name: "Grenada", currency: "XCD" },
  GP: { name: "Guadeloupe", currency: "EUR" },
  GT: { name: "Guatemala", currency: "GTQ" },
  HT: { name: "Haiti", currency: "HTG" },
  HN: { name: "Honduras", currency: "HNL" },
  JM: { name: "Jamaica", currency: "JMD" },
  MQ: { name: "Martinique", currency: "EUR" },
  MX: { name: "Mexico", currency: "MXN" },
  MS: { name: "Montserrat", currency: "XCD" },
  NI: { name: "Nicaragua", currency: "NIO" },
  PA: { name: "Panama", currency: "PAB" },
  PM: { name: "Saint Pierre and Miquelon", currency: "EUR" },
  BL: { name: "Saint Barthélemy", currency: "EUR" },
  KN: { name: "Saint Kitts and Nevis", currency: "XCD" },
  LC: { name: "Saint Lucia", currency: "XCD" },
  MF: { name: "Saint Martin", currency: "EUR" },
  VC: { name: "Saint Vincent and the Grenadines", currency: "XCD" },
  SX: { name: "Sint Maarten", currency: "ANG" },
  TT: { name: "Trinidad and Tobago", currency: "TTD" },
  TC: { name: "Turks and Caicos Islands", currency: "USD" },
  US: { name: "United States", currency: "USD" },
  VI: { name: "U.S. Virgin Islands", currency: "USD" },

  // South America
  AR: { name: "Argentina", currency: "ARS" },
  BO: { name: "Bolivia", currency: "BOB" },
  BR: { name: "Brazil", currency: "BRL" },
  CL: { name: "Chile", currency: "CLP" },
  CO: { name: "Colombia", currency: "COP" },
  EC: { name: "Ecuador", currency: "USD" },
  FK: { name: "Falkland Islands", currency: "FKP" },
  GF: { name: "French Guiana", currency: "EUR" },
  GY: { name: "Guyana", currency: "GYD" },
  PY: { name: "Paraguay", currency: "PYG" },
  PE: { name: "Peru", currency: "PEN" },
  SR: { name: "Suriname", currency: "SRD" },
  UY: { name: "Uruguay", currency: "UYU" },
  VE: { name: "Venezuela", currency: "VES" },

  // Oceania
  AS: { name: "American Samoa", currency: "USD" },
  AU: { name: "Australia", currency: "AUD" },
  CK: { name: "Cook Islands", currency: "NZD" },
  FJ: { name: "Fiji", currency: "FJD" },
  PF: { name: "French Polynesia", currency: "XPF" },
  GU: { name: "Guam", currency: "USD" },
  KI: { name: "Kiribati", currency: "AUD" },
  MH: { name: "Marshall Islands", currency: "USD" },
  FM: { name: "Micronesia", currency: "USD" },
  NR: { name: "Nauru", currency: "AUD" },
  NC: { name: "New Caledonia", currency: "XPF" },
  NZ: { name: "New Zealand", currency: "NZD" },
  NU: { name: "Niue", currency: "NZD" },
  NF: { name: "Norfolk Island", currency: "AUD" },
  MP: { name: "Northern Mariana Islands", currency: "USD" },
  PW: { name: "Palau", currency: "USD" },
  PG: { name: "Papua New Guinea", currency: "PGK" },
  PN: { name: "Pitcairn Islands", currency: "NZD" },
  WS: { name: "Samoa", currency: "WST" },
  SB: { name: "Solomon Islands", currency: "SBD" },
  TK: { name: "Tokelau", currency: "NZD" },
  TO: { name: "Tonga", currency: "TOP" },
  TV: { name: "Tuvalu", currency: "AUD" },
  VU: { name: "Vanuatu", currency: "VUV" },
  WF: { name: "Wallis and Futuna", currency: "XPF" },
} as const;

export type RegionCode = keyof typeof SUPPORTED_REGIONS;

export const DEFAULT_REGION = {
  region: "US",
  regionName: "United States",
  currency: DEFAULT_CURRENCY,
  timezone: "America/New_York",
  language: DEFAULT_LANGUAGE,
};
