export enum ErrorCode {
  INTERNAL_SERVER_ERROR = "ERR_500",
  NOT_IMPLEMENTED = "ERR_501",
  TOO_MANY_REQUESTS = "ERR_429",
  BAD_GATEWAY = "ERR_502",
  SERVICE_UNAVAILABLE = "ERR_503",
  GATEWAY_TIMEOUT = "ERR_504",
  METHOD_NOT_ALLOWED = "ERR_405",

  // Authentication errors
  INVALID_CREDENTIALS = "AUTH_001",
  ACCOUNT_DEACTIVATED = "AUTH_002",
  EMAIL_NOT_VERIFIED = "AUTH_003",
  INVALID_REFRESH_TOKEN = "AUTH_004",
  NO_TOKEN_PROVIDED = "AUTH_005",
  INVALID_TOKEN = "AUTH_006",
  USER_ALREADY_EXISTS = "AUTH_007",
  EMAIL_ALREADY_VERIFIED = "AUTH_008",
  USER_NOT_FOUND = "AUTH_009",
  INVALID_VERIFICATION_TOKEN = "AUTH_010",
  EXPIRED_VERIFICATION_TOKEN = "AUTH_011",
  INVALID_RESET_TOKEN = "AUTH_012",
  EXPIRED_RESET_TOKEN = "AUTH_013",
  GOOGLE_AUTH_FAILED = "AUTH_014",
  GOOGLE_USER_INFO_FAILED = "AUTH_015",

  // User errors
  USER_NOT_FOUND_USER = "USER_001",
  EMAIL_ALREADY_IN_USE = "USER_002",
  USERNAME_ALREADY_IN_USE = "USER_003",
  INVALID_USER_DATA = "USER_004",
  CANNOT_UPDATE_EMAIL = "USER_005",
  INVALID_ROLE = "USER_006",
  CANNOT_CHANGE_OWN_ROLE = "USER_007",
  INSUFFICIENT_PERMISSIONS = "USER_008",
  USER_ALREADY_ACTIVE = "USER_009",
  USER_ALREADY_DEACTIVATED = "USER_010",
  CANNOT_DEACTIVATE_SELF = "USER_011",
  INVALID_PROFILE_DATA = "USER_012",
  PROFILE_UPDATE_FAILED = "USER_013",

  GYM_NOT_FOUND = "GYM_001",
  CREATE_GYM_FAILED = "GYM_002",
  FETCH_GYMS_FAILED = "GYM_003",
  FETCH_MY_GYMS_FAILED = "GYM_004",
  FETCH_MEMBER_GYMS_FAILED = "GYM_005",
  FETCH_ALL_MY_GYMS_FAILED = "GYM_006",
  UPDATE_GYM_FAILED = "GYM_007",
  DELETE_GYM_FAILED = "GYM_008",
}

export const HttpStatusToErrorCode: Record<number, ErrorCode> = {
  // 400 Bad Request
  400: ErrorCode.INVALID_USER_DATA,

  // 401 Unauthorized
  401: ErrorCode.INVALID_CREDENTIALS,

  // 403 Forbidden
  403: ErrorCode.INSUFFICIENT_PERMISSIONS,

  // 404 Not Found
  404: ErrorCode.USER_NOT_FOUND,

  // 405 Method Not Allowed
  405: ErrorCode.METHOD_NOT_ALLOWED,

  // 409 Conflict
  409: ErrorCode.USER_ALREADY_EXISTS,

  // 422 Unprocessable Entity
  422: ErrorCode.INVALID_USER_DATA,

  // 429 Too Many Requests
  429: ErrorCode.TOO_MANY_REQUESTS,

  // 500 Internal Server Error
  500: ErrorCode.INTERNAL_SERVER_ERROR,

  // 501 Not Implemented
  501: ErrorCode.NOT_IMPLEMENTED,

  // 502 Bad Gateway
  502: ErrorCode.BAD_GATEWAY,

  // 503 Service Unavailable
  503: ErrorCode.SERVICE_UNAVAILABLE,

  // 504 Gateway Timeout
  504: ErrorCode.GATEWAY_TIMEOUT,
};
